In [10]:
from sklearn.datasets import load_iris
iris = load_iris()

In [11]:
X = iris.data
y = iris.target

In [12]:
print (X.shape)
print (y.shape)

(150, 4)
(150,)


In [13]:
import pandas as pd
pd.DataFrame(X, columns = iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
print (y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [17]:
knn.predict([[3,5,4,2]])

array([1])

In [18]:
#example text for training (SMS messages)

simple_train = ['call you tonight', 'Call me a cab', 'please call me...PLEASE!']



In [35]:
# example response vector
is_desperate = [0,0,1]
# 세번재 것이 desperate하다는 dictionary


In [21]:
#learn the 'vocabulary' of the traning data
from sklearn.feature_extraction.text import CountVectorizer
 
vect = CountVectorizer()

In [22]:
#learn the 'vocabulary' of the training data ( occurs in-place)
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [23]:
# examine the fitted vocabulary
vect.get_feature_names()

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [25]:
# transform training data into a 'documnet - terix'
simple_train_dtm= vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [26]:
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [27]:
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [29]:
#examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [30]:
# Bag of word

#check the type of the document-term matrix

type (simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [31]:
#example the sparse matrix contents

print (simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [36]:
#build a model to predict desperation

knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(simple_train_dtm, is_desperate)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [37]:
#example text for model testing
simple_test = ["please don't call me"]

In [38]:
# transform testing data into a documnet-term matrix
#using existing vocabulary

simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [39]:
#examine the vocabulary and documnet term matrix togetherpd.
pd.DataFrame(simple_test_dtm.toarray(), columns = vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

In [40]:
#predict whether simpe_test is desperate
knn.predict(simple_test_dtm)

#This is desperate

array([1])

### 좀 더 큰 데이터셋으로

In [44]:
#read file into pandas
sms = pd.read_table('sms.tsv', header = None, names=['label', 'message'])


In [45]:
#examine the shape
sms.shape

(5572, 2)

In [46]:
#examine the first 10 rows
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [47]:
#exampe the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [48]:
#convert label to a numberical viable
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [49]:
#check that the conversion worked
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [50]:
#how to define X and y (from the iris data ) for use with a MODEL
X = iris.data
y = iris.target

print (X.shape)
print (y.shape)

(150, 4)
(150,)


In [55]:
#how to define X and y (from the SMS data) for use with COUNTVECTORIZER
X = sms.message
y = sms.label_num

print (X.shape)
print (y.shape)

(5572,)
(5572,)


In [58]:
#split X and y into training and testing sets
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)


(4179,)
(1393,)
(4179,)
(1393,)


## 데이터셋을 벡터화하기


In [62]:
#instantiate the vectorizer
vect = CountVectorizer()

In [64]:
#learn training data vocabulary, then use it to create a 
# document-term matrix

vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [66]:
#equivalently : combine fit and transform into a single step
# fit 과 transform을 한번에 할 수 있다
X_train_dtm = vect.fit_transform(X_train)

In [68]:
#examine the document-term matrix
X_train_dtm
#This is usually sparse matrix

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [70]:
#transform testing data (using fitted vocabulary)
#into a document-term matrix
X_test_dtm = vect.transform(X_test)
# test는 따로 fit 없이 바로 transform
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

#split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


prnt (X_train)

## 모델 만들고 평가하기


In [71]:
#import and instantiate a logistic regression model

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

In [74]:
#train tne model using X_train_dtm
%time logreg.fit(X_train_dtm, y_train)

Wall time: 46.3 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [75]:
#make class tredictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [76]:
y_pred_class

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [78]:
#cacluate predicted probablilities for X-test_dtm

y_pred_prob= logreg.predict_proba(X_test_dtm)[:, 1] # 확률을 계산한듯

y_pred_prob

array([ 0.01269556,  0.00347183,  0.00616517, ...,  0.03354907,
        0.99725053,  0.00157706])

In [79]:
from sklearn.metrics import accuracy_score, roc_auc_score



In [80]:
#calculate accuracy of class predictions
accuracy_score(y_test, y_pred_class)

0.9877961234745154

In [81]:
roc_auc_score(y_test, y_pred_prob)

0.99368176123143015

## TF-IDF


In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [87]:
simple_train =  ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [88]:
vect = TfidfVectorizer()

In [90]:
vect.fit_transform(simple_train).toarray()

array([[ 0.        ,  0.38537163,  0.        ,  0.        ,  0.65249088,
         0.65249088],
       [ 0.72033345,  0.42544054,  0.54783215,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.26607496,  0.34261996,  0.90100815,  0.        ,
         0.        ]])

In [92]:
vect.get_feature_names()

['cab', 'call', 'me', 'please', 'tonight', 'you']